// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/design-system/DirectionA.tsx": () => import("../components/mockups/design-system/DirectionA.tsx"),
  "./components/mockups/design-system/DirectionB.tsx": () => import("../components/mockups/design-system/DirectionB.tsx"),
  "./components/mockups/design-system/DirectionC.tsx": () => import("../components/mockups/design-system/DirectionC.tsx")
};
